src/Entity/Quiz.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\QuizRepository")
 * @ORM\Table(name="tbl_quiz")
 */
class Quiz
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $summary;

    /**
     * @ORM\Column(type="integer")
     */
    private $number_of_questions;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->categories = new ArrayCollection();

        $this->setCreatedAt(new \DateTime());
        $this->setUpdatedAt(new \DateTime());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(?string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getNumberOfQuestions(): ?int
    {
        return $this->number_of_questions;
    }

    public function setNumberOfQuestions(int $number_of_questions): self
    {
        $this->number_of_questions = $number_of_questions;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/QuizType.php
<?php

namespace App\Form;

use App\Entity\Quiz;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuizType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('summary')
            ->add('number_of_questions')
            ->add('active')
            // ->add('created_at')
            // ->add('updated_at')
        ;

        $builder->add('categories', EntityType::class, array(
            'class' => Category::class,
            'choice_label' => 'longname',
            'multiple' => true
        ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Quiz::class,
        ]);
    }
}

src/Controller/QuizController.php
<?php

namespace App\Controller;

use App\Entity\Quiz;
use App\Form\QuizType;
use App\Repository\QuizRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/quiz")
 */
class QuizController extends AbstractController
{
    /**
     * @Route("/", name="quiz_index", methods={"GET"})
     */
    public function index(QuizRepository $quizRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        return $this->render('quiz/index.html.twig', [
            'quizzes' => $quizRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="quiz_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $quiz = new Quiz();
        $form = $this->createForm(QuizType::class, $quiz);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($quiz);
            $entityManager->flush();

            return $this->redirectToRoute('quiz_index');
        }

        return $this->render('quiz/new.html.twig', [
            'quiz' => $quiz,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="quiz_show", methods={"GET"})
     */
    public function show(Quiz $quiz): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        return $this->render('quiz/show.html.twig', [
            'quiz' => $quiz,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="quiz_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Quiz $quiz): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $form = $this->createForm(QuizType::class, $quiz);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $quiz->setUpdatedAt(new \DateTime());
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('quiz_index');
        }

        return $this->render('quiz/edit.html.twig', [
            'quiz' => $quiz,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="quiz_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Quiz $quiz): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        if ($this->isCsrfTokenValid('delete'.$quiz->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($quiz);
            $entityManager->flush();
        }

        return $this->redirectToRoute('quiz_index');
    }
}

templates/quiz/_delete_form.html.twig
<form method="post" action="{{ path('quiz_delete', {'id': quiz.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ quiz.id) }}">
    <button class="btn">Delete</button>
</form>

templates/quiz/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/quiz/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Quiz{% endblock %}

{% block body %}
    <h1>Edit Quiz</h1>

    {{ include('quiz/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('quiz_index') }}">back to list</a>

    {{ include('quiz/_delete_form.html.twig') }}
{% endblock %}

templates/quiz/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quiz index{% endblock %}

{% block body %}
    <h1>Quiz index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Summary</th>
                <th>Number_of_questions</th>
                <th>Active</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for quiz in quizzes %}
            <tr>
                <td>{{ quiz.id }}</td>
                <td>{{ quiz.title }}</td>
                <td>{{ quiz.summary }}</td>
                <td>{{ quiz.numberOfQuestions }}</td>
                <td>{{ quiz.active ? 'Yes' : 'No' }}</td>
                <td>{{ quiz.createdAt ? quiz.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ quiz.updatedAt ? quiz.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('quiz_show', {'id': quiz.id}) }}">show</a>
                    <a href="{{ path('quiz_edit', {'id': quiz.id}) }}">edit</a>
                </td>
                <td>
                    {% for categorie in Quiz.categories %}
                        {{ Category.quizzes }}
                    {% endfor %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('quiz_new') }}">Create new</a>
{% endblock %}

templates/quiz/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Quiz{% endblock %}

{% block body %}
    <h1>Create new Quiz</h1>

    {{ include('quiz/_form.html.twig') }}

    <a href="{{ path('quiz_index') }}">back to list</a>
{% endblock %}

templates/quiz/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quiz{% endblock %}

{% block body %}
    <h1>Quiz</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ quiz.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ quiz.title }}</td>
            </tr>
            <tr>
                <th>Summary</th>
                <td>{{ quiz.summary }}</td>
            </tr>
            <tr>
                <th>Number_of_questions</th>
                <td>{{ quiz.numberOfQuestions }}</td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ quiz.active ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <td>
                        {% for categorie in Quiz.categories %}
                            {{ Category.quizzes }}
                        {% endfor %}
                </td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('quiz_index') }}">back to list</a>

    <a href="{{ path('quiz_edit', {'id': quiz.id}) }}">edit</a>

    {{ include('quiz/_delete_form.html.twig') }}
{% endblock %}